# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  timeFormat: "02.01.06"
  showRandomTip: false
  nerdFontsVersion: "3"
  commitHashLength: 7
  border: rounded
git:
  pagers:
    - colorArg: never
      pager: delta --dark --paging=never
